// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DpeZak.Database.Models;

public partial class Asws
{
    public string AswName { get; set; } = null!;

    public int ItemPos { get; set; }

    public string? ItemValue { get; set; }

    public string? ItemDisplay { get; set; }

    public string? ErfasstVon { get; set; }

    public DateTime? ErfasstAm { get; set; }

    public string? GeaendertVon { get; set; }

    public DateTime? GeaendertAm { get; set; }

    public int? AnzahlAenderungen { get; set; }

    public string? Bemerkung { get; set; }
}