// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DpeZak.Database.Models;

public partial class Fltr
{
    public string Form { get; set; } = null!;

    public string Name { get; set; } = null!;

    public string? Fltrlist { get; set; }

    public string? Keyfields { get; set; }

    public string? Ispublic { get; set; }

    public int FltrId { get; set; }

    public string? ErfasstVon { get; set; }

    public DateTime? ErfasstAm { get; set; }

    public string? ErfasstDatenbank { get; set; }

    public string? GeaendertVon { get; set; }

    public DateTime? GeaendertAm { get; set; }

    public string? GeaendertDatenbank { get; set; }

    public int? AnzahlAenderungen { get; set; }

    public string? Bemerkung { get; set; }

    public string? Columnlist { get; set; }
}