// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using IndexAttribute = Microsoft.EntityFrameworkCore.IndexAttribute;

namespace DpeZak.Database.Models;

[Table("INITIALISIERUNGEN", Schema = "QUSY")]
[Index("ANWENDUNG", "TYP", "NAME", "SECTION", "PARAM", Name = "UK_INIT", IsUnique = true)]
public partial class INITIALISIERUNGEN
{
    [StringLength(30)]
    [Unicode(false)]
    public string ANWENDUNG { get; set; } = null!;

    [StringLength(1)]
    [Unicode(false)]
    public string TYP { get; set; } = null!;

    [StringLength(30)]
    [Unicode(false)]
    public string NAME { get; set; } = null!;

    [StringLength(255)]
    [Unicode(false)]
    public string SECTION { get; set; } = null!;

    [StringLength(255)]
    [Unicode(false)]
    public string PARAM { get; set; } = null!;

    [StringLength(255)]
    [Unicode(false)]
    public string WERT { get; set; } = null!;

    [Key]
    [Precision(9)]
    public int INIT_ID { get; set; }

    [StringLength(30)]
    [Unicode(false)]
    public string? ERFASST_VON { get; set; }

    [Column(TypeName = "DATE")]
    public DateTime? ERFASST_AM { get; set; }

    [StringLength(30)]
    [Unicode(false)]
    public string? ERFASST_DATENBANK { get; set; }

    [StringLength(30)]
    [Unicode(false)]
    public string? GEAENDERT_VON { get; set; }

    [Column(TypeName = "DATE")]
    public DateTime? GEAENDERT_AM { get; set; }

    [StringLength(30)]
    [Unicode(false)]
    public string? GEAENDERT_DATENBANK { get; set; }

    [Precision(9)]
    public int? ANZAHL_AENDERUNGEN { get; set; }

    [StringLength(2000)]
    [Unicode(false)]
    public string? BEMERKUNG { get; set; }
}