// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using IndexAttribute = Microsoft.EntityFrameworkCore.IndexAttribute;

namespace DpeZak.Database.Models;

[Table("KONTINGENTE", Schema = "PINFO")]
[Index("MARA_NR", "KUNW_NR", "WERK_NR", "DATUM_VON", "AKTIV", Name = "UK_KONT", IsUnique = true)]
public partial class KONTINGENTE
{
    [Key]
    [Precision(9)]
    public int KONT_ID { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string? KUNW_NR { get; set; }

    [StringLength(18)]
    [Unicode(false)]
    public string MARA_NR { get; set; } = null!;

    [StringLength(4)]
    [Unicode(false)]
    public string WERK_NR { get; set; } = null!;

    [StringLength(1)]
    [Unicode(false)]
    public string AKTIV { get; set; } = null!;

    [Column(TypeName = "DATE")]
    public DateTime? DATUM_VON { get; set; }

    [Column(TypeName = "DATE")]
    public DateTime? DATUM_BIS { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string? VT_LKW { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string? VT_BAHN { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string? VT_VERPACKT { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string? VT_LOSE { get; set; }

    [Column(TypeName = "NUMBER(9,3)")]
    public decimal? MENGE_SOLL { get; set; }

    [Precision(5)]
    public short? ANZAHL_SOLL { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string? RESERVIERT { get; set; }

    [Column(TypeName = "NUMBER(9,3)")]
    public decimal? MENGE_IST { get; set; }

    [Precision(5)]
    public short? ANZAHL_IST { get; set; }

    [Column(TypeName = "DATE")]
    public DateTime? DATUM_IST { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string? SPERRGRUND { get; set; }

    [StringLength(35)]
    [Unicode(false)]
    public string? KUNW_NAME1 { get; set; }

    [StringLength(35)]
    [Unicode(false)]
    public string? KUNW_NAME2 { get; set; }

    [StringLength(35)]
    [Unicode(false)]
    public string? KUNW_STRASSE { get; set; }

    [StringLength(3)]
    [Unicode(false)]
    public string? KUNW_LAND { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string? KUNW_PLZ { get; set; }

    [StringLength(35)]
    [Unicode(false)]
    public string? KUNW_ORT { get; set; }

    [StringLength(40)]
    [Unicode(false)]
    public string? MARA_NAME { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string? SILO_CHECK { get; set; }

    [Precision(7)]
    public int? SILP1_NR { get; set; }

    [Precision(7)]
    public int? SILP2_NR { get; set; }

    [Precision(7)]
    public int? SILP3_NR { get; set; }

    [Column(TypeName = "NUMBER(5,2)")]
    public decimal? ANTEIL1 { get; set; }

    [Column(TypeName = "NUMBER(5,2)")]
    public decimal? ANTEIL2 { get; set; }

    [Column(TypeName = "NUMBER(5,2)")]
    public decimal? ANTEIL3 { get; set; }

    [Precision(7)]
    public int? SW1_SILP1_NR { get; set; }

    [Precision(7)]
    public int? SW1_SILP2_NR { get; set; }

    [Precision(7)]
    public int? SW1_SILP3_NR { get; set; }

    [Column(TypeName = "NUMBER(5,2)")]
    public decimal? SW1_ANTEIL1 { get; set; }

    [Column(TypeName = "NUMBER(5,2)")]
    public decimal? SW1_ANTEIL2 { get; set; }

    [Column(TypeName = "NUMBER(5,2)")]
    public decimal? SW1_ANTEIL3 { get; set; }

    [Precision(7)]
    public int? SW2_SILP1_NR { get; set; }

    [Precision(7)]
    public int? SW2_SILP2_NR { get; set; }

    [Precision(7)]
    public int? SW2_SILP3_NR { get; set; }

    [Column(TypeName = "NUMBER(5,2)")]
    public decimal? SW2_ANTEIL1 { get; set; }

    [Column(TypeName = "NUMBER(5,2)")]
    public decimal? SW2_ANTEIL2 { get; set; }

    [Column(TypeName = "NUMBER(5,2)")]
    public decimal? SW2_ANTEIL3 { get; set; }

    [Column(TypeName = "NUMBER(9,3)")]
    public decimal? SILP1_RES { get; set; }

    [Column(TypeName = "NUMBER(9,3)")]
    public decimal? SILP2_RES { get; set; }

    [Column(TypeName = "NUMBER(9,3)")]
    public decimal? SILP3_RES { get; set; }

    [Column(TypeName = "NUMBER(9,3)")]
    public decimal? SW1_SILP1_RES { get; set; }

    [Column(TypeName = "NUMBER(9,3)")]
    public decimal? SW1_SILP2_RES { get; set; }

    [Column(TypeName = "NUMBER(9,3)")]
    public decimal? SW1_SILP3_RES { get; set; }

    [Column(TypeName = "NUMBER(9,3)")]
    public decimal? SW2_SILP1_RES { get; set; }

    [Column(TypeName = "NUMBER(9,3)")]
    public decimal? SW2_SILP2_RES { get; set; }

    [Column(TypeName = "NUMBER(9,3)")]
    public decimal? SW2_SILP3_RES { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string? REPLIKATION { get; set; }

    [StringLength(30)]
    [Unicode(false)]
    public string? ERFASST_VON { get; set; }

    [Column(TypeName = "DATE")]
    public DateTime? ERFASST_AM { get; set; }

    [StringLength(30)]
    [Unicode(false)]
    public string? ERFASST_DATENBANK { get; set; }

    [StringLength(30)]
    [Unicode(false)]
    public string? GEAENDERT_VON { get; set; }

    [Column(TypeName = "DATE")]
    public DateTime? GEAENDERT_AM { get; set; }

    [StringLength(30)]
    [Unicode(false)]
    public string? GEAENDERT_DATENBANK { get; set; }

    [Precision(9)]
    public int? ANZAHL_AENDERUNGEN { get; set; }

    [StringLength(2000)]
    [Unicode(false)]
    public string? BEMERKUNG { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string? UMLAGERUNG { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string? VERSUCHSLAUF { get; set; }

    [Precision(7)]
    public int? VERS_SILP1_NR { get; set; }

    [Precision(7)]
    public int? VERS_SILP2_NR { get; set; }

    [Precision(7)]
    public int? VERS_SILP3_NR { get; set; }

    [Column(TypeName = "NUMBER(5,2)")]
    public decimal? VERS_ANTEIL1 { get; set; }

    [Column(TypeName = "NUMBER(5,2)")]
    public decimal? VERS_ANTEIL2 { get; set; }

    [Column(TypeName = "NUMBER(5,2)")]
    public decimal? VERS_ANTEIL3 { get; set; }

    [Column(TypeName = "NUMBER(9,3)")]
    public decimal? VERS_MENGE { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string? CHECK_SILOSTAND { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string? CHECK_SILOSPERRE { get; set; }
}