// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DpeZak.Database.Models;

public partial class Kund
{
    public string? KugrNr { get; set; }

    public int KundNr { get; set; }

    public string? BeziNr { get; set; }

    public string? KundAnrede { get; set; }

    public string? KundNa1 { get; set; }

    public string? KundNa2 { get; set; }

    public string? KundStr { get; set; }

    public string? KundHnr { get; set; }

    public string? KundLand { get; set; }

    public string? KundLcode { get; set; }

    public string? KundPlz { get; set; }

    public string? KundOrt { get; set; }

    public string? KundAnspr { get; set; }

    public string? KundTel { get; set; }

    public string? KundFax { get; set; }

    public string? KundZatyp { get; set; }

    public string? KundAnl { get; set; }

    public string? KundErz { get; set; }

    public string? KundEnts { get; set; }

    public string? KundZah { get; set; }

    public string? KundEdv { get; set; }

    public string? KundDivers { get; set; }

    public string? KundFktyp { get; set; }

    public string? KundErznr { get; set; }

    public string? KundBefnr { get; set; }

    public string? KundEntnr { get; set; }

    public double? KundFrmen { get; set; }

    public DateTime? KundFrdtm { get; set; }

    public short? KundFksor { get; set; }

    public short? KundFktur { get; set; }

    public short? KundAnzlfs { get; set; }

    public short? KundAnzre { get; set; }

    public string? KugrName { get; set; }

    public string? KundGes1 { get; set; }

    public string? KundGes2 { get; set; }

    public string? ErfasstVon { get; set; }

    public DateTime? ErfasstAm { get; set; }

    public string? GeaendertVon { get; set; }

    public DateTime? GeaendertAm { get; set; }

    public int? AnzahlAenderungen { get; set; }

    public string? Bemerkung { get; set; }

    public string? KundDisk { get; set; }

    public string? EntgeltDru { get; set; }

    public string? SammelKto { get; set; }

    public string? Lastschrift { get; set; }

    public string? Bankkonto { get; set; }

    public string? Bankleitzahl { get; set; }

    public string? Bankname { get; set; }

    public string? Bankort { get; set; }

    public string? Buergschaft { get; set; }

    public decimal? BuergschaftBetrag { get; set; }

    public string? Rechtext { get; set; }

    public string Bonitaet { get; set; } = null!;

    public string? LastschriftBmhk { get; set; }

    public string? Bmhk { get; set; }

    public string? Barerlaubt { get; set; }

    public string? Email { get; set; }

    public string? Www { get; set; }

    public string? FibuLfrtNr { get; set; }

    public string? EanvFirma { get; set; }

    public string? EanvZertifikat { get; set; }

    public string? EanvAdre { get; set; }

    public string? EanvDiffadre { get; set; }

    public string? KundFkgruEn { get; set; }

    public string? KundBeziIntern { get; set; }

    public string? KundNa3 { get; set; }

    public string? KundNa4 { get; set; }

    public string? KundStr2 { get; set; }

    public string? KundOrt2 { get; set; }

    public double? OpMaxbetrag { get; set; }

    public string? Iban { get; set; }

    public string? Bic { get; set; }

    public DateTime? Dtllzah { get; set; }

    public int? KundZahNr { get; set; }

    public string? Ustid { get; set; }

    public string? KundFkgruSr { get; set; }

    public string? KundGugruSr { get; set; }

    public virtual Bezi? BeziNrNavigation { get; set; }
}