// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using IndexAttribute = Microsoft.EntityFrameworkCore.IndexAttribute;

namespace DpeZak.Database.Models;

[Table("KUNDENVEREINBARUNGEN", Schema = "PINFO")]
[Index("KUNW_NR", "MARA_NR", "WERK_NR", "KATEGORIE", "POS", Name = "UK_KUVE", IsUnique = true)]
public partial class KUNDENVEREINBARUNGEN
{
    [StringLength(10)]
    [Unicode(false)]
    public string KUNW_NR { get; set; } = null!;

    [StringLength(18)]
    [Unicode(false)]
    public string? MARA_NR { get; set; }

    [StringLength(6)]
    [Unicode(false)]
    public string? WERK_NR { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string AKTIV { get; set; } = null!;

    [Column(TypeName = "DATE")]
    public DateTime? DATUM_VON { get; set; }

    [Column(TypeName = "DATE")]
    public DateTime? DATUM_BIS { get; set; }

    [Precision(6)]
    public int POS { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string KATEGORIE { get; set; } = null!;

    [Precision(9)]
    public int? AKTION_NR { get; set; }

    [StringLength(2000)]
    [Unicode(false)]
    public string? MELDUNG { get; set; }

    [StringLength(35)]
    [Unicode(false)]
    public string? KUNW_NAME1 { get; set; }

    [StringLength(35)]
    [Unicode(false)]
    public string? KUNW_NAME2 { get; set; }

    [StringLength(35)]
    [Unicode(false)]
    public string? KUNW_STRASSE { get; set; }

    [StringLength(3)]
    [Unicode(false)]
    public string? KUNW_LAND { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string? KUNW_PLZ { get; set; }

    [StringLength(35)]
    [Unicode(false)]
    public string? KUNW_ORT { get; set; }

    [StringLength(40)]
    [Unicode(false)]
    public string? MARA_NAME { get; set; }

    [Key]
    [Precision(9)]
    public int KUVE_ID { get; set; }

    [StringLength(30)]
    [Unicode(false)]
    public string? ERFASST_VON { get; set; }

    [Column(TypeName = "DATE")]
    public DateTime? ERFASST_AM { get; set; }

    [StringLength(30)]
    [Unicode(false)]
    public string? ERFASST_DATENBANK { get; set; }

    [StringLength(30)]
    [Unicode(false)]
    public string? GEAENDERT_VON { get; set; }

    [Column(TypeName = "DATE")]
    public DateTime? GEAENDERT_AM { get; set; }

    [StringLength(30)]
    [Unicode(false)]
    public string? GEAENDERT_DATENBANK { get; set; }

    [Precision(9)]
    public int? ANZAHL_AENDERUNGEN { get; set; }

    [StringLength(2000)]
    [Unicode(false)]
    public string? BEMERKUNG { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string? VT_LKW { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string? VT_BAHN { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string? VT_VERPACKT { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string? VT_LOSE { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string? FEUCHTE_PRINT { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string? FEUCHTE_CHECK { get; set; }

    [Column(TypeName = "NUMBER(5,2)")]
    public decimal? WARN_FEUCHTE { get; set; }

    [Column(TypeName = "NUMBER(5,2)")]
    public decimal? SPERR_FEUCHTE { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string? VB_QUITT { get; set; }

    [Column(TypeName = "NUMBER(5,2)")]
    public decimal? MELDEN_STUNDEN { get; set; }

    [Column(TypeName = "NUMBER(5,2)")]
    public decimal? MELDEN_FUELLST { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string? KONT_PFLICHT { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string? PROBE_SW { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string? VORKASSE { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string? VERSANDAVIS { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string? EMAIL { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string? MELDE_KAT { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string? MUSTER { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string? PROBE { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string? SORTE_KNZ { get; set; }

    [Precision(2)]
    public byte? ANZ_LFS { get; set; }

    [Column(TypeName = "NUMBER(6,3)")]
    public decimal? MK_SGU { get; set; }

    [Column(TypeName = "NUMBER(6,3)")]
    public decimal? MK_SGO { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string? LAB_WZ_FREQ { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string? ERSATZ_MARA_NR { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string? MISCHEN { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string? KUMMULIERT { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string? TSVORBE { get; set; }

    [StringLength(18)]
    [Unicode(false)]
    public string? TS_MARA_NR { get; set; }

    [Column(TypeName = "NUMBER(5,2)")]
    public decimal? TS_MENGE { get; set; }

    [Column(TypeName = "NUMBER(9,3)")]
    public decimal? MAX_BRUTTO { get; set; }

    [Column(TypeName = "NUMBER(9,3)")]
    public decimal? MAX_NETTO { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string? MITAUFLIEGER { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string? AUFT_PFLICHT { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string? SCHIFFCONTAINER { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string? ANALYSEPROBE { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string? ANALYSEPROBE_KW { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string? ANALYSEPROBE_TAG { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string? PROBE_AUSWAHL { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string? ANALYSEKAMMER { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string? PEKR_NR { get; set; }

    [StringLength(40)]
    [Unicode(false)]
    public string? SIEB_SGU { get; set; }

    [StringLength(40)]
    [Unicode(false)]
    public string? SIEB_SGO { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string? WZ_ART { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string? WZ_BEZUG { get; set; }

    [Precision(3)]
    public byte? WZ_TAGE { get; set; }

    [StringLength(80)]
    [Unicode(false)]
    public string? WZ_VORLAGE { get; set; }

    [StringLength(40)]
    [Unicode(false)]
    public string? BELADEFOLGE { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string? NULLMENGESAP { get; set; }

    [Precision(7)]
    public int? SILP1_NR { get; set; }

    [Precision(7)]
    public int? SILP2_NR { get; set; }

    [Precision(7)]
    public int? SILP3_NR { get; set; }

    [Precision(7)]
    public int? SW1_SILP1_NR { get; set; }

    [Precision(7)]
    public int? SW1_SILP2_NR { get; set; }

    [Precision(7)]
    public int? SW1_SILP3_NR { get; set; }

    [Precision(7)]
    public int? SW2_SILP1_NR { get; set; }

    [Precision(7)]
    public int? SW2_SILP2_NR { get; set; }

    [Precision(7)]
    public int? SW2_SILP3_NR { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string? LFS_ANHANG { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string? KUNR_KNZ { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string? VERLADESPERRE { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string? KUNDEN_BC { get; set; }

    [StringLength(30)]
    [Unicode(false)]
    public string? BC_TYP { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string? BC_INHALT { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string? ROLLE_KUNW { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string? ROLLE_KUNR { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string? ROLLE_SPED { get; set; }

    [StringLength(30)]
    [Unicode(false)]
    public string? REST_FLTR_ART { get; set; }

    [Column(TypeName = "NUMBER(9,3)")]
    public decimal? REST_MIN_TO { get; set; }

    [Precision(5)]
    public short? REST_VORB_TAGE { get; set; }

    [Precision(4)]
    public byte? BEIMISCHUNG_SPS_CODE { get; set; }

    [Column(TypeName = "NUMBER(5,2)")]
    public decimal? BEIMISCHUNG_PROZ { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string? SOFORTEXPORT { get; set; }
}