// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DpeZak.Database.Models;

public partial class RDatn
{
    public string Ordner { get; set; } = null!;

    public string Filename { get; set; } = null!;

    public DateTime? Filetime { get; set; }

    public byte[]? Inhalt { get; set; }

    public int DatnId { get; set; }

    public string? ErfasstVon { get; set; }

    public DateTime? ErfasstAm { get; set; }

    public string? ErfasstDatenbank { get; set; }

    public int? AnzahlAenderungen { get; set; }

    public DateTime? GeaendertAm { get; set; }

    public string? GeaendertVon { get; set; }

    public string? GeaendertDatenbank { get; set; }

    public string? Bemerkung { get; set; }
}