// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DpeZak.Database.Models;

public partial class Vbez
{
    public string VbezNr { get; set; } = null!;

    public string? VbezBez { get; set; }

    public string? ErfasstVon { get; set; }

    public DateTime? ErfasstAm { get; set; }

    public string? GeaendertVon { get; set; }

    public DateTime? GeaendertAm { get; set; }

    public int? AnzahlAenderungen { get; set; }

    public string? Bemerkung { get; set; }

    public virtual ICollection<Bezi> Bezi { get; set; } = new List<Bezi>();
}