// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace QwTest7.Database.Models;

public partial class QuvaContext : DbContext
{
    public QuvaContext(DbContextOptions<QuvaContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AUSWAHLEN> AUSWAHLEN { get; set; }

    public virtual DbSet<DATEIEN> DATEIEN { get; set; }

    public virtual DbSet<FAHRZEUGE> FAHRZEUGE { get; set; }

    public virtual DbSet<FILTERABFRAGEN> FILTERABFRAGEN { get; set; }

    public virtual DbSet<INITIALISIERUNGEN> INITIALISIERUNGEN { get; set; }

    public virtual DbSet<KARTEN> KARTEN { get; set; }

    public virtual DbSet<KONTINGENTE> KONTINGENTE { get; set; }

    public virtual DbSet<KUNDENVEREINBARUNGEN> KUNDENVEREINBARUNGEN { get; set; }

    public virtual DbSet<SPEDITIONEN> SPEDITIONEN { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.HasDefaultSchema("QUVA");

        modelBuilder.Entity<AUSWAHLEN>(entity =>
        {
            entity.HasKey(e => e.ASWS_ID).HasName("PK_ASWS");

            entity.Property(e => e.ANZAHL_AENDERUNGEN).ValueGeneratedOnAdd();
            entity.Property(e => e.ERFASST_AM).ValueGeneratedOnAdd();
            entity.Property(e => e.ERFASST_DATENBANK).ValueGeneratedOnAdd();
            entity.Property(e => e.GEAENDERT_AM).ValueGeneratedOnAdd();
        });

        modelBuilder.Entity<DATEIEN>(entity =>
        {
            entity.HasKey(e => e.DATN_ID).HasName("PK_DATN");

            entity.Property(e => e.ANZAHL_AENDERUNGEN).ValueGeneratedOnAdd();
            entity.Property(e => e.ERFASST_AM).ValueGeneratedOnAdd();
            entity.Property(e => e.ERFASST_DATENBANK).ValueGeneratedOnAdd();
            entity.Property(e => e.GEAENDERT_AM).ValueGeneratedOnAdd();
            entity.Property(e => e.GEAENDERT_DATENBANK).ValueGeneratedOnAdd();
            entity.Property(e => e.INHALT).HasDefaultValueSql("EMPTY_BLOB()");
        });

        modelBuilder.Entity<FAHRZEUGE>(entity =>
        {
            entity.HasKey(e => e.FRZG_ID).HasName("PK_FRZG");

            entity.Property(e => e.ANZAHL_AENDERUNGEN).ValueGeneratedOnAdd();
            entity.Property(e => e.BEMERKUNG).ValueGeneratedOnAdd();
            entity.Property(e => e.ERFASST_AM).ValueGeneratedOnAdd();
            entity.Property(e => e.ERFASST_DATENBANK).ValueGeneratedOnAdd();
            entity.Property(e => e.FAHRZEUGTYP).ValueGeneratedOnAdd();
            entity.Property(e => e.FLAGS).ValueGeneratedOnAdd();
            entity.Property(e => e.GEAENDERT_AM).ValueGeneratedOnAdd();
            entity.Property(e => e.GEAENDERT_DATENBANK).ValueGeneratedOnAdd();
            entity.Property(e => e.MAX_BRUTTO).ValueGeneratedOnAdd();
            entity.Property(e => e.REPLIKATION).ValueGeneratedOnAdd();
            entity.Property(e => e.SPEDITION).ValueGeneratedOnAdd();
            entity.Property(e => e.SPED_ID).ValueGeneratedOnAdd();
            entity.Property(e => e.TARA_DATUM).ValueGeneratedOnAdd();
            entity.Property(e => e.TARA_FREI_ANZAHL).ValueGeneratedOnAdd();
            entity.Property(e => e.TARA_GEWICHT).ValueGeneratedOnAdd();
            entity.Property(e => e.TRANSPORTMITTEL).ValueGeneratedOnAdd();
            entity.Property(e => e.WERK_NR).ValueGeneratedOnAdd();

            entity.HasOne(d => d.SPED).WithMany(p => p.FAHRZEUGE).HasConstraintName("FK_FRZG_SPED");
        });

        modelBuilder.Entity<FILTERABFRAGEN>(entity =>
        {
            entity.HasKey(e => e.FLTR_ID).HasName("PK_FLTR");

            entity.Property(e => e.ANWE).HasDefaultValueSql("'QUSY'                ");
            entity.Property(e => e.ANZAHL_AENDERUNGEN).ValueGeneratedOnAdd();
            entity.Property(e => e.ERFASST_AM).ValueGeneratedOnAdd();
            entity.Property(e => e.ERFASST_DATENBANK).ValueGeneratedOnAdd();
            entity.Property(e => e.GEAENDERT_AM).ValueGeneratedOnAdd();
            entity.Property(e => e.GEAENDERT_DATENBANK).ValueGeneratedOnAdd();
        });

        modelBuilder.Entity<INITIALISIERUNGEN>(entity =>
        {
            entity.HasKey(e => e.INIT_ID).HasName("PK_INIT");

            entity.Property(e => e.ANZAHL_AENDERUNGEN).ValueGeneratedOnAdd();
            entity.Property(e => e.ERFASST_AM).ValueGeneratedOnAdd();
            entity.Property(e => e.ERFASST_DATENBANK).ValueGeneratedOnAdd();
            entity.Property(e => e.GEAENDERT_AM).ValueGeneratedOnAdd();
            entity.Property(e => e.GEAENDERT_DATENBANK).ValueGeneratedOnAdd();
        });

        modelBuilder.Entity<KARTEN>(entity =>
        {
            entity.HasKey(e => e.KART_ID).HasName("PK_KART");

            entity.Property(e => e.ANZAHL_AENDERUNGEN).ValueGeneratedOnAdd();
            entity.Property(e => e.AUFBAU).ValueGeneratedOnAdd();
            entity.Property(e => e.AUFK_NR).ValueGeneratedOnAdd();
            entity.Property(e => e.BEMERKUNG).ValueGeneratedOnAdd();
            entity.Property(e => e.EINGANG_KNZ)
                .ValueGeneratedOnAdd()
                .HasDefaultValueSql("'N'");
            entity.Property(e => e.ERFASST_AM).ValueGeneratedOnAdd();
            entity.Property(e => e.ERFASST_DATENBANK).ValueGeneratedOnAdd();
            entity.Property(e => e.FREMDWAEGUNG)
                .ValueGeneratedOnAdd()
                .HasDefaultValueSql("'N'");
            entity.Property(e => e.FRZG_ID).ValueGeneratedOnAdd();
            entity.Property(e => e.GEAENDERT_AM).ValueGeneratedOnAdd();
            entity.Property(e => e.GEAENDERT_DATENBANK).ValueGeneratedOnAdd();
            entity.Property(e => e.GEAENDERT_VON).ValueGeneratedOnAdd();
            entity.Property(e => e.KART_NR).ValueGeneratedOnAdd();
            entity.Property(e => e.KOMBI_KNZ).HasDefaultValueSql("'N'\n");
            entity.Property(e => e.KUND_KNZ)
                .ValueGeneratedOnAdd()
                .HasDefaultValueSql("'J'");
            entity.Property(e => e.KUNW_NR).ValueGeneratedOnAdd();
            entity.Property(e => e.MARA_NR).ValueGeneratedOnAdd();
            entity.Property(e => e.MAX_BRUTTO).ValueGeneratedOnAdd();
            entity.Property(e => e.ORI_KART_NR).ValueGeneratedOnAdd();
            entity.Property(e => e.PEKR_BEZ).ValueGeneratedOnAdd();
            entity.Property(e => e.PEKR_ID).ValueGeneratedOnAdd();
            entity.Property(e => e.PEKR_NR).ValueGeneratedOnAdd();
            entity.Property(e => e.PROBENPFLICHT)
                .ValueGeneratedOnAdd()
                .HasDefaultValueSql("'J'");
            entity.Property(e => e.REPLIKATION).ValueGeneratedOnAdd();
            entity.Property(e => e.SILO_NR).ValueGeneratedOnAdd();
            entity.Property(e => e.SOLLMENGE).ValueGeneratedOnAdd();
            entity.Property(e => e.SORTE_KNZ)
                .ValueGeneratedOnAdd()
                .HasDefaultValueSql("'N'");
            entity.Property(e => e.SPEDITION).ValueGeneratedOnAdd();
            entity.Property(e => e.SPED_ID).ValueGeneratedOnAdd();
            entity.Property(e => e.SPENDER_KNZ)
                .ValueGeneratedOnAdd()
                .HasDefaultValueSql("'N'");
            entity.Property(e => e.SPERR_KNZ)
                .ValueGeneratedOnAdd()
                .HasDefaultValueSql("'N'");
            entity.Property(e => e.TARA_DATUM).ValueGeneratedOnAdd();
            entity.Property(e => e.TARA_GEWICHT).ValueGeneratedOnAdd();
            entity.Property(e => e.TEILMENGE1).ValueGeneratedOnAdd();
            entity.Property(e => e.TEILMENGE2).ValueGeneratedOnAdd();
            entity.Property(e => e.TEILMENGE3).ValueGeneratedOnAdd();
            entity.Property(e => e.TEILMENGE4).ValueGeneratedOnAdd();
            entity.Property(e => e.TEILMENGE5).ValueGeneratedOnAdd();
            entity.Property(e => e.TRANSPORTMITTEL).ValueGeneratedOnAdd();
            entity.Property(e => e.TROCKEN_FEUCHT).ValueGeneratedOnAdd();
            entity.Property(e => e.WERK_NR).ValueGeneratedOnAdd();

            entity.HasOne(d => d.FRZG).WithMany(p => p.KARTEN).HasConstraintName("FK_KART_FRZG");

            entity.HasOne(d => d.SPED).WithMany(p => p.KARTEN).HasConstraintName("FK_KART_SPED");
        });

        modelBuilder.Entity<KONTINGENTE>(entity =>
        {
            entity.HasKey(e => e.KONT_ID).HasName("PK_KONT");

            entity.Property(e => e.AKTIV)
                .ValueGeneratedOnAdd()
                .HasDefaultValueSql("'J'                   ")
                .IsFixedLength();
            entity.Property(e => e.ANTEIL1).ValueGeneratedOnAdd();
            entity.Property(e => e.ANTEIL2).ValueGeneratedOnAdd();
            entity.Property(e => e.ANTEIL3).ValueGeneratedOnAdd();
            entity.Property(e => e.ANZAHL_AENDERUNGEN).ValueGeneratedOnAdd();
            entity.Property(e => e.ANZAHL_IST).ValueGeneratedOnAdd();
            entity.Property(e => e.ANZAHL_SOLL).ValueGeneratedOnAdd();
            entity.Property(e => e.BEMERKUNG).ValueGeneratedOnAdd();
            entity.Property(e => e.CHECK_SILOSPERRE).HasDefaultValueSql("'N'\n");
            entity.Property(e => e.CHECK_SILOSTAND).HasDefaultValueSql("'N'");
            entity.Property(e => e.DATUM_BIS).ValueGeneratedOnAdd();
            entity.Property(e => e.DATUM_IST).ValueGeneratedOnAdd();
            entity.Property(e => e.DATUM_VON).ValueGeneratedOnAdd();
            entity.Property(e => e.ERFASST_AM).ValueGeneratedOnAdd();
            entity.Property(e => e.ERFASST_DATENBANK).ValueGeneratedOnAdd();
            entity.Property(e => e.GEAENDERT_AM).ValueGeneratedOnAdd();
            entity.Property(e => e.GEAENDERT_DATENBANK).ValueGeneratedOnAdd();
            entity.Property(e => e.KUNW_LAND).ValueGeneratedOnAdd();
            entity.Property(e => e.KUNW_NAME1).ValueGeneratedOnAdd();
            entity.Property(e => e.KUNW_NAME2).ValueGeneratedOnAdd();
            entity.Property(e => e.KUNW_NR).ValueGeneratedOnAdd();
            entity.Property(e => e.KUNW_ORT).ValueGeneratedOnAdd();
            entity.Property(e => e.KUNW_PLZ).ValueGeneratedOnAdd();
            entity.Property(e => e.KUNW_STRASSE).ValueGeneratedOnAdd();
            entity.Property(e => e.MARA_NAME).ValueGeneratedOnAdd();
            entity.Property(e => e.MARA_NR).ValueGeneratedOnAdd();
            entity.Property(e => e.MENGE_IST).ValueGeneratedOnAdd();
            entity.Property(e => e.MENGE_SOLL).ValueGeneratedOnAdd();
            entity.Property(e => e.REPLIKATION).ValueGeneratedOnAdd();
            entity.Property(e => e.RESERVIERT)
                .ValueGeneratedOnAdd()
                .HasDefaultValueSql("'J'");
            entity.Property(e => e.SILO_CHECK)
                .HasDefaultValueSql("'J'")
                .IsFixedLength();
            entity.Property(e => e.SILP1_NR).ValueGeneratedOnAdd();
            entity.Property(e => e.SILP1_RES).ValueGeneratedOnAdd();
            entity.Property(e => e.SILP2_NR).ValueGeneratedOnAdd();
            entity.Property(e => e.SILP2_RES).ValueGeneratedOnAdd();
            entity.Property(e => e.SILP3_NR).ValueGeneratedOnAdd();
            entity.Property(e => e.SILP3_RES).ValueGeneratedOnAdd();
            entity.Property(e => e.SPERRGRUND).ValueGeneratedOnAdd();
            entity.Property(e => e.SW1_ANTEIL1).ValueGeneratedOnAdd();
            entity.Property(e => e.SW1_ANTEIL2).ValueGeneratedOnAdd();
            entity.Property(e => e.SW1_ANTEIL3).ValueGeneratedOnAdd();
            entity.Property(e => e.SW1_SILP1_NR).ValueGeneratedOnAdd();
            entity.Property(e => e.SW1_SILP1_RES).ValueGeneratedOnAdd();
            entity.Property(e => e.SW1_SILP2_NR).ValueGeneratedOnAdd();
            entity.Property(e => e.SW1_SILP2_RES).ValueGeneratedOnAdd();
            entity.Property(e => e.SW1_SILP3_NR).ValueGeneratedOnAdd();
            entity.Property(e => e.SW1_SILP3_RES).ValueGeneratedOnAdd();
            entity.Property(e => e.SW2_ANTEIL1).ValueGeneratedOnAdd();
            entity.Property(e => e.SW2_ANTEIL2).ValueGeneratedOnAdd();
            entity.Property(e => e.SW2_ANTEIL3).ValueGeneratedOnAdd();
            entity.Property(e => e.SW2_SILP1_NR).ValueGeneratedOnAdd();
            entity.Property(e => e.SW2_SILP1_RES).ValueGeneratedOnAdd();
            entity.Property(e => e.SW2_SILP2_NR).ValueGeneratedOnAdd();
            entity.Property(e => e.SW2_SILP2_RES).ValueGeneratedOnAdd();
            entity.Property(e => e.SW2_SILP3_NR).ValueGeneratedOnAdd();
            entity.Property(e => e.SW2_SILP3_RES).ValueGeneratedOnAdd();
            entity.Property(e => e.UMLAGERUNG)
                .ValueGeneratedOnAdd()
                .HasDefaultValueSql("'N'");
            entity.Property(e => e.VERSUCHSLAUF).HasDefaultValueSql("'N'");
            entity.Property(e => e.VT_BAHN)
                .ValueGeneratedOnAdd()
                .HasDefaultValueSql("'J'")
                .IsFixedLength();
            entity.Property(e => e.VT_LKW)
                .ValueGeneratedOnAdd()
                .HasDefaultValueSql("'J'")
                .IsFixedLength();
            entity.Property(e => e.VT_LOSE)
                .ValueGeneratedOnAdd()
                .HasDefaultValueSql("'J'")
                .IsFixedLength();
            entity.Property(e => e.VT_VERPACKT)
                .ValueGeneratedOnAdd()
                .HasDefaultValueSql("'J'")
                .IsFixedLength();
            entity.Property(e => e.WERK_NR).ValueGeneratedOnAdd();
        });

        modelBuilder.Entity<KUNDENVEREINBARUNGEN>(entity =>
        {
            entity.HasKey(e => e.KUVE_ID).HasName("PK_KUVE");

            entity.Property(e => e.AKTION_NR).ValueGeneratedOnAdd();
            entity.Property(e => e.AKTIV)
                .ValueGeneratedOnAdd()
                .HasDefaultValueSql("'J'                   ")
                .IsFixedLength();
            entity.Property(e => e.ANALYSEKAMMER)
                .ValueGeneratedOnAdd()
                .HasDefaultValueSql("'N'");
            entity.Property(e => e.ANALYSEPROBE)
                .ValueGeneratedOnAdd()
                .HasDefaultValueSql("'N'");
            entity.Property(e => e.ANALYSEPROBE_KW)
                .ValueGeneratedOnAdd()
                .HasDefaultValueSql("'N'");
            entity.Property(e => e.ANALYSEPROBE_TAG)
                .ValueGeneratedOnAdd()
                .HasDefaultValueSql("'N'");
            entity.Property(e => e.ANZAHL_AENDERUNGEN).ValueGeneratedOnAdd();
            entity.Property(e => e.ANZ_LFS).ValueGeneratedOnAdd();
            entity.Property(e => e.AUFT_PFLICHT)
                .ValueGeneratedOnAdd()
                .HasDefaultValueSql("'N'");
            entity.Property(e => e.BC_INHALT).ValueGeneratedOnAdd();
            entity.Property(e => e.BC_TYP).ValueGeneratedOnAdd();
            entity.Property(e => e.BEIMISCHUNG_PROZ).ValueGeneratedOnAdd();
            entity.Property(e => e.BEIMISCHUNG_SPS_CODE).ValueGeneratedOnAdd();
            entity.Property(e => e.BELADEFOLGE).ValueGeneratedOnAdd();
            entity.Property(e => e.BEMERKUNG).ValueGeneratedOnAdd();
            entity.Property(e => e.DATUM_BIS).ValueGeneratedOnAdd();
            entity.Property(e => e.DATUM_VON).ValueGeneratedOnAdd();
            entity.Property(e => e.EMAIL).ValueGeneratedOnAdd();
            entity.Property(e => e.ERFASST_AM).ValueGeneratedOnAdd();
            entity.Property(e => e.ERFASST_DATENBANK).ValueGeneratedOnAdd();
            entity.Property(e => e.ERSATZ_MARA_NR).ValueGeneratedOnAdd();
            entity.Property(e => e.FEUCHTE_CHECK)
                .ValueGeneratedOnAdd()
                .HasDefaultValueSql("'N'");
            entity.Property(e => e.FEUCHTE_PRINT)
                .ValueGeneratedOnAdd()
                .HasDefaultValueSql("'N'");
            entity.Property(e => e.GEAENDERT_AM).ValueGeneratedOnAdd();
            entity.Property(e => e.GEAENDERT_DATENBANK).ValueGeneratedOnAdd();
            entity.Property(e => e.KATEGORIE)
                .ValueGeneratedOnAdd()
                .IsFixedLength();
            entity.Property(e => e.KONT_PFLICHT)
                .ValueGeneratedOnAdd()
                .HasDefaultValueSql("'N'");
            entity.Property(e => e.KUMMULIERT)
                .ValueGeneratedOnAdd()
                .HasDefaultValueSql("'N'");
            entity.Property(e => e.KUNDEN_BC)
                .ValueGeneratedOnAdd()
                .HasDefaultValueSql("'N'");
            entity.Property(e => e.KUNR_KNZ)
                .ValueGeneratedOnAdd()
                .HasDefaultValueSql("'N'\n");
            entity.Property(e => e.KUNW_LAND).ValueGeneratedOnAdd();
            entity.Property(e => e.KUNW_NAME1).ValueGeneratedOnAdd();
            entity.Property(e => e.KUNW_NAME2).ValueGeneratedOnAdd();
            entity.Property(e => e.KUNW_NR).ValueGeneratedOnAdd();
            entity.Property(e => e.KUNW_ORT).ValueGeneratedOnAdd();
            entity.Property(e => e.KUNW_PLZ).ValueGeneratedOnAdd();
            entity.Property(e => e.KUNW_STRASSE).ValueGeneratedOnAdd();
            entity.Property(e => e.LAB_WZ_FREQ).ValueGeneratedOnAdd();
            entity.Property(e => e.LFS_ANHANG)
                .ValueGeneratedOnAdd()
                .HasDefaultValueSql("'N'");
            entity.Property(e => e.MARA_NAME).ValueGeneratedOnAdd();
            entity.Property(e => e.MARA_NR).ValueGeneratedOnAdd();
            entity.Property(e => e.MAX_BRUTTO).ValueGeneratedOnAdd();
            entity.Property(e => e.MAX_NETTO).ValueGeneratedOnAdd();
            entity.Property(e => e.MELDEN_FUELLST).ValueGeneratedOnAdd();
            entity.Property(e => e.MELDEN_STUNDEN).ValueGeneratedOnAdd();
            entity.Property(e => e.MELDE_KAT)
                .ValueGeneratedOnAdd()
                .HasDefaultValueSql("'0'")
                .IsFixedLength();
            entity.Property(e => e.MELDUNG).ValueGeneratedOnAdd();
            entity.Property(e => e.MISCHEN)
                .ValueGeneratedOnAdd()
                .HasDefaultValueSql("'N'");
            entity.Property(e => e.MITAUFLIEGER).ValueGeneratedOnAdd();
            entity.Property(e => e.MK_SGO).ValueGeneratedOnAdd();
            entity.Property(e => e.MK_SGU).ValueGeneratedOnAdd();
            entity.Property(e => e.MUSTER)
                .ValueGeneratedOnAdd()
                .HasDefaultValueSql("'N'")
                .IsFixedLength();
            entity.Property(e => e.NULLMENGESAP).ValueGeneratedOnAdd();
            entity.Property(e => e.PEKR_NR).ValueGeneratedOnAdd();
            entity.Property(e => e.POS).ValueGeneratedOnAdd();
            entity.Property(e => e.PROBE)
                .ValueGeneratedOnAdd()
                .HasDefaultValueSql("'N'")
                .IsFixedLength();
            entity.Property(e => e.PROBE_AUSWAHL)
                .ValueGeneratedOnAdd()
                .HasDefaultValueSql("'N'");
            entity.Property(e => e.PROBE_SW)
                .ValueGeneratedOnAdd()
                .HasDefaultValueSql("'N'");
            entity.Property(e => e.REST_FLTR_ART).ValueGeneratedOnAdd();
            entity.Property(e => e.REST_MIN_TO).ValueGeneratedOnAdd();
            entity.Property(e => e.REST_VORB_TAGE).ValueGeneratedOnAdd();
            entity.Property(e => e.ROLLE_KUNR)
                .ValueGeneratedOnAdd()
                .HasDefaultValueSql("'J'");
            entity.Property(e => e.ROLLE_KUNW)
                .ValueGeneratedOnAdd()
                .HasDefaultValueSql("'J'");
            entity.Property(e => e.ROLLE_SPED)
                .ValueGeneratedOnAdd()
                .HasDefaultValueSql("'N'\n");
            entity.Property(e => e.SCHIFFCONTAINER)
                .ValueGeneratedOnAdd()
                .HasDefaultValueSql("'N'");
            entity.Property(e => e.SIEB_SGO).ValueGeneratedOnAdd();
            entity.Property(e => e.SIEB_SGU).ValueGeneratedOnAdd();
            entity.Property(e => e.SILP1_NR).ValueGeneratedOnAdd();
            entity.Property(e => e.SILP2_NR).ValueGeneratedOnAdd();
            entity.Property(e => e.SILP3_NR).ValueGeneratedOnAdd();
            entity.Property(e => e.SOFORTEXPORT).ValueGeneratedOnAdd();
            entity.Property(e => e.SORTE_KNZ)
                .ValueGeneratedOnAdd()
                .HasDefaultValueSql("'N'");
            entity.Property(e => e.SPERR_FEUCHTE).ValueGeneratedOnAdd();
            entity.Property(e => e.SW1_SILP1_NR).ValueGeneratedOnAdd();
            entity.Property(e => e.SW1_SILP2_NR).ValueGeneratedOnAdd();
            entity.Property(e => e.SW1_SILP3_NR).ValueGeneratedOnAdd();
            entity.Property(e => e.SW2_SILP1_NR).ValueGeneratedOnAdd();
            entity.Property(e => e.SW2_SILP2_NR).ValueGeneratedOnAdd();
            entity.Property(e => e.SW2_SILP3_NR).ValueGeneratedOnAdd();
            entity.Property(e => e.TSVORBE).ValueGeneratedOnAdd();
            entity.Property(e => e.TS_MARA_NR).ValueGeneratedOnAdd();
            entity.Property(e => e.TS_MENGE).ValueGeneratedOnAdd();
            entity.Property(e => e.VB_QUITT)
                .ValueGeneratedOnAdd()
                .HasDefaultValueSql("'N'");
            entity.Property(e => e.VERLADESPERRE)
                .ValueGeneratedOnAdd()
                .HasDefaultValueSql("'N'\n");
            entity.Property(e => e.VERSANDAVIS)
                .ValueGeneratedOnAdd()
                .HasDefaultValueSql("'N'")
                .IsFixedLength();
            entity.Property(e => e.VORKASSE)
                .ValueGeneratedOnAdd()
                .HasDefaultValueSql("'N'")
                .IsFixedLength();
            entity.Property(e => e.VT_BAHN)
                .ValueGeneratedOnAdd()
                .HasDefaultValueSql("'J'")
                .IsFixedLength();
            entity.Property(e => e.VT_LKW)
                .ValueGeneratedOnAdd()
                .HasDefaultValueSql("'J'")
                .IsFixedLength();
            entity.Property(e => e.VT_LOSE)
                .ValueGeneratedOnAdd()
                .HasDefaultValueSql("'J'")
                .IsFixedLength();
            entity.Property(e => e.VT_VERPACKT)
                .ValueGeneratedOnAdd()
                .HasDefaultValueSql("'J'")
                .IsFixedLength();
            entity.Property(e => e.WARN_FEUCHTE).ValueGeneratedOnAdd();
            entity.Property(e => e.WERK_NR).ValueGeneratedOnAdd();
            entity.Property(e => e.WZ_ART)
                .ValueGeneratedOnAdd()
                .HasDefaultValueSql("NULL ");
            entity.Property(e => e.WZ_BEZUG)
                .ValueGeneratedOnAdd()
                .HasDefaultValueSql("NULL ");
            entity.Property(e => e.WZ_TAGE).ValueGeneratedOnAdd();
            entity.Property(e => e.WZ_VORLAGE).ValueGeneratedOnAdd();
        });

        modelBuilder.Entity<SPEDITIONEN>(entity =>
        {
            entity.HasKey(e => e.SPED_ID).HasName("PK_SPED");

            entity.Property(e => e.ANZAHL_AENDERUNGEN).ValueGeneratedOnAdd();
            entity.Property(e => e.BEMERKUNG).ValueGeneratedOnAdd();
            entity.Property(e => e.ERFASST_AM).ValueGeneratedOnAdd();
            entity.Property(e => e.ERFASST_DATENBANK).ValueGeneratedOnAdd();
            entity.Property(e => e.GEAENDERT_AM).ValueGeneratedOnAdd();
            entity.Property(e => e.GEAENDERT_DATENBANK).ValueGeneratedOnAdd();
            entity.Property(e => e.KREDITOR_NR).ValueGeneratedOnAdd();
            entity.Property(e => e.NAME_LANG).ValueGeneratedOnAdd();
            entity.Property(e => e.PALETTENKONTO)
                .ValueGeneratedOnAdd()
                .HasDefaultValueSql("'N'\n");
            entity.Property(e => e.PAL_INV_BST_D).ValueGeneratedOnAdd();
            entity.Property(e => e.PAL_INV_BST_E).ValueGeneratedOnAdd();
            entity.Property(e => e.PAL_INV_DTM).ValueGeneratedOnAdd();
            entity.Property(e => e.REPLIKATION).ValueGeneratedOnAdd();
            entity.Property(e => e.SPED_NAME).ValueGeneratedOnAdd();
            entity.Property(e => e.WERK_NR).ValueGeneratedOnAdd();
        });
        modelBuilder.HasSequence("ALLG_ID_S", "QUSY");
        modelBuilder.HasSequence("ANWE_ID_S", "QUSY");
        modelBuilder.HasSequence("ASWS_ID_S", "QUSY");
        modelBuilder.HasSequence("BATA_ID_S", "QUSY");
        modelBuilder.HasSequence("DATN_ID_S", "QUSY");
        modelBuilder.HasSequence("FELD_ID_S", "QUSY");
        modelBuilder.HasSequence("FLOG_ID_S", "QUSY");
        modelBuilder.HasSequence("FLTR_ID_S", "QUSY");
        modelBuilder.HasSequence("FMEL_ID_S", "QUSY");
        modelBuilder.HasSequence("FOFO_ID_S", "QUSY");
        modelBuilder.HasSequence("FORM_ID_S", "QUSY");
        modelBuilder.HasSequence("GRUP_ID_S", "QUSY");
        modelBuilder.HasSequence("INIT_ID_S", "QUSY");
        modelBuilder.HasSequence("KONT_ID_S", "PINFO");
        modelBuilder.HasSequence("KRGR_ID_S", "QUSY");
        modelBuilder.HasSequence("KRIT_ID_S", "QUSY");
        modelBuilder.HasSequence("KUVE_ID_S", "PINFO");
        modelBuilder.HasSequence("KVSH_ID_S", "PINFO");
        modelBuilder.HasSequence("OBJE_ID_S", "QUSY");
        modelBuilder.HasSequence("PRAE_ID_S", "QUSY");
        modelBuilder.HasSequence("PROG_ID_S", "QUSY");
        modelBuilder.HasSequence("QUAL_ID_S", "PINFO");
        modelBuilder.HasSequence("RECH_ID_S", "QUSY");
        modelBuilder.HasSequence("REFO_ID_S", "QUSY");
        modelBuilder.HasSequence("REPO_ID_S", "QUSY");
        modelBuilder.HasSequence("SYSP_ID_S", "QUSY");
        modelBuilder.HasSequence("T_FELD_ID_S", "QUSY");
        modelBuilder.HasSequence("USER_ID_S", "QUSY");
        modelBuilder.HasSequence("USGR_ID_S", "QUSY");
        modelBuilder.HasSequence("VEAN_ID_S", "PINFO");

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}